// <auto-generated />
namespace Taha.DatabaseInitilization.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class xxx3xx : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(xxx3xx));
        
        string IMigrationMetadata.Id
        {
            get { return "201808232328095_xxx3xx"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
